p = 0.127                   # tube pitch (m)
d_in = 9.5 / 1000           # tube inner diameter(m)
r_o = 5 / 1000              # tube outer radius(m)
r_in = d_in / 2             # tube inner radius(m)
flow_area = 3.14 * r_in**2  # flow area(m2)
delta_glass = 3.81 / 1000   # cover thickness
delta_insul = 50.8 / 1000   # insulation thickness(m)
delta_abs = 0.015           # absorber thickness(m)
delta_a = 0.025             # air gap thickness(m)
cp_glass = 720              # cover specific heat (J/kg.K)
cp_insul = 1030             # insulation specific heat (J/kg.K)
rho_glass = 2500            # cover density(Kg/m^3)
rho_insul = 70              # insulation density(Kg/m^3)
alpha = 0.005               # absorption coefficient
tau_alpha = 0.861           # effictive transmittance-absorption coef.
k_insul = 0.035             # insulation thermal conductivity(W/m.K)
cp_abs = 385                # absorber specific heat (J/kg.K)
rho_abs = 8795              # absorber density(Kg/m^3)
cp_air = 1.0056e003         # air specific heat (J/kg.K)
length = 1.9                # collector length (m)
width = 0.92                # collector width (m)
g = 9.81                    # gravitational acceleration (m/s2)
segma = 5.6697 * 10**-8     # Stephan-Bolzmann constant (W/m2.k4)
emi_glass = 0.88            # glass emissivity
emi_abs = 0.1               # absorber emissivity
emi_insul = 0.05            # insulation emissivity
