import matplotlib.pyplot as plt
import numpy as np

def plots(time_steps, dtau, t_gc, t_ac, t_abc, t_fc, t_ic, t_am, t_in,t_out, Q_dot,eff):
    T = time_steps * dtau
    fig = plt.figure(figsize=(10, 5))
    plt.subplot(2, 2, 1)
    plt.plot(T, t_gc, label="t_gc")
    plt.plot(T, t_ac, label="t_ac")
    plt.plot(T, t_abc, label="t_abc")
    plt.plot(T, t_fc, label="t_fc")
    plt.plot(T, t_ic, label="t_ic")
    plt.plot(T, t_am[1:len(time_steps) + 1], label="t_am")
    plt.legend(loc='center left', bbox_to_anchor=(1, 0.5))
    plt.xlabel("time (s)")
    plt.ylabel("Temperature (K)")
    plt.subplot(2, 2, 2)
    plt.plot(T, t_in, label="t_in")
    plt.plot(T, t_out, label="t_out")
    plt.plot(T, t_fc, label="t_fc")
    plt.xlabel("time (s)")
    plt.ylabel("Temperature (K)")
    plt.legend(loc='center left', bbox_to_anchor=(1, 0.5))
    plt.subplot(2, 2, 3)
    plt.plot(T, Q_dot)
    plt.ylabel("Q_dot")
    plt.subplot(2, 2, 4)
    plt.plot(T, eff)
    plt.ylabel("eff")
    plt.tight_layout()
    plt.show()